sudo: false
language: ruby
rvm:
  - "2.2.0"
  - "2.1.5"
before_script:
  - gem install bundler -v 1.11.2
  - gem install rake

script: 'cd octo-core && rake spec'
bundler_args: '--without=debug'
services:
  - cassandra
